import Head from "next/head";
import Image from "next/image";
import ModalA from "../src/components/ModalA";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Chakra UI Project</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ModalA />
    </div>
  );
}
